Repository libp2p/go-libp2p-routing, pull requests merged in 2018-09, with the labels that each got.

#26 fix the error documentation
  routing.go
Labels: discussion, documentation, in progress

#25 SearchValue
  .gx/lastpubver
  package.json
  routing.go
Labels: enhancement, in progress

#28 gx publish 2.6.1
  .gx/lastpubver
  package.json
Labels: in progress

#29 SearchValue: redefine search behaviour
  routing.go
Labels: in progress
